# 345M
Global:
  device: gpu
  seed: 1024


Engine:
  max_steps: 2000000
  num_train_epochs: 1
  accumulate_steps: 
  logging_freq: 1
  eval_freq: 2000
  eval_iters: 10
  mix_precision:
    use_pure_fp16: True
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 50000
    output_dir: ./output
    ckpt_dir:


Data:
  batch_size:
    global_batch_size:
    local_batch_size: 16
    micro_batch_size: 16

  dataset:
    input_dir: ./data
    split: '949,50,1'
    max_seq_len: 1024


Model:
  vocab_size: 50304
  hidden_size: 1024
  num_layers: 24
  num_attention_heads: 16
  ffn_hidden_size: 4096
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity: 'full_attn'
  fused_linear: True
  

Distributed:
  dp_degree:
  mp_degree: 1
  pp_degree: 1
  virtual_pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False


Fused:
  tensor_fusion: False


Optimizer:
  # name: Adam
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1.0e-8
  lr:
    decay_steps: 360000
    warmup_rate: 0.01
    max_lr: 3.0e-4
    min_lr: 1.0e-5
  grad_clip: 1.0


Generation:
  top_k: 50
  top_p: 0.75
  temperature: 1.0
  min_dec_len: 1
  max_dec_len: 200
  num_return_sequences: 1
  decode_strategy: "sampling"
