Global:
  device: gpu
  seed: 1024
  binary_head: True
  
  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1


Engine:
  max_steps: 500000
  num_train_epochs: 1
  accumulate_steps: 1
  logging_freq: 1
  eval_freq: 500000
  eval_iters: 10
  test_iters: -1
  mix_precision:
    use_pure_fp16: False
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 50000
    save_epoch: 1
    output_dir: ./output
    ckpt_dir:


Model:
  module: "ErnieModule"
  name: "Ernie"
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 512
  type_vocab_size: 2
  initializer_range: 0.02
  pad_token_id: 0
  task_type_vocab_size: 3
  task_id: 0
  use_task_id: False
  use_recompute: False  


Data:
  Train:
    dataset:
      name: ErnieDataset
      input_dir: /workspace/workspace/PaddleNLP/model_zoo/ernie-1.0/data
      tokenizer_type: ernie-1.0-base-zh-cw
      split: [949, 50, 1]
      mode: Train
      max_seq_length: 512
      masked_lm_prob: 0.15
      short_seq_prob: 0.1
      seed: 1024
      share_folder: False
      favor_longer_ngram: False
      max_ngrams: 3

    sampler:
      name: GPTBatchSampler
      shuffle: False
      drop_last: True
    loader:
      num_workers: 0
      return_list: False
      collate_fn: 
        name: ErnieCollateData
        micro_batch_size: 
  
  Eval:
    dataset:
      name: ErnieDataset
      input_dir: /workspace/workspace/PaddleNLP/model_zoo/ernie-1.0/data
      tokenizer_type: ernie-1.0-base-zh-cw
      split: [949, 50, 1]
      mode: Eval
      max_seq_length: 512
      masked_lm_prob: 0.15
      short_seq_prob: 0.1
      seed: 1024
      share_folder: False
      favor_longer_ngram: False
      max_ngrams: 3

    sampler:
      name: GPTBatchSampler
      shuffle: False
      drop_last: True

    loader:
      num_workers: 1
      return_list: False
      collate_fn: 
        name: ErnieCollateData
        micro_batch_size: 1

Optimizer:
  name: FusedAdamW
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  lr:
    name: CosineAnnealingWithWarmupDecay
    decay_steps: 990000
    warmup_rate: 0.01
    max_lr: 0.0001
    min_lr: 0.00001
  grad_clip:
    name: "ClipGradByGlobalNorm"
    clip_norm: 1.0
  tensor_fusion: False


Profiler:
  enable: False
  scheduler: [1, 5]
  profiler_log: profiler_log
  detailed: False


Inference:
  model_dir: ./output
  mp_degree: 1
