_base_: ./pretrain_ernie_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 8
  micro_batch_size: 1


Model:
  vocab_size: 40000
  hidden_size: 768
  num_hidden_layers: 8
  num_attention_heads: 16
  intermediate_size: 
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 512
  type_vocab_size: 4
  initializer_range: 0.02
  pad_token_id: 0
  task_type_vocab_size: 3
  task_id: 0
  use_task_id: True
  use_recompute: False

Data:
  Train:
    dataset:
      tokenizer_type: ernie-1.0-base-zh-cw
  Eval:
    dataset:
      tokenizer_type: ernie-1.0-base-zh-cw


Distributed:
  dp_degree: 2
  mp_degree: 2
  pp_degree: 2
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
