Global:
  device: gpu
  seed: 1024

  global_batch_size: 
  local_batch_size: 1
  micro_batch_size: 1


Engine:
  max_steps: 2500000
  num_train_epochs: 1
  accumulate_steps: 1
  logging_freq: 10
  eval_freq: 10000000
  eval_iters: 10000000
  mix_precision:
    use_pure_fp16: False 
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 10000
    output_dir: ./output
    ckpt_dir:


Model:
  module: "ImagenModule"
  name: "Imagen"
  fused_linear: False

# data loader for train
Data:
  Train:
    dataset:
      name: ImagenDataset
      input_path: ./projects/imagen/filelist/laion_400M/train
      shuffle: True
      image_format: base64 
      image_size: 64 
      text_max_len: 128 
      filter_image_resolution: 64
    loader:
      num_workers: 8
      shuffle: True
      batch_size: 16 
      drop_last: True
      collate_fn: imagen_collate_fn
  

Fused:
  tensor_fusion: False


Optimizer:
  name: Adam
  weight_decay: 0.
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  lr:
    name: CosineAnnealingWithWarmupDecay
    decay_steps: 2500000
    warmup_rate: 0.025 
    max_lr: 1.0e-4
    min_lr: 0.0
  grad_clip:
    name: "ClipGradByGlobalNorm"
    clip_norm: 1.0


Profiler:
  enable: False
  scheduler: [1, 5]
  profiler_log: profiler_log
  detailed: False


Inference:
  model_dir: ./output
  mp_degree: 1
