_base_: ./pretrain_gpt_345M_single_card.yaml


Model:
  module: GPTEvalModule


Offline_Eval:
  eval_path: lambada_test.jsonl
  cloze_eval: True
  overlapping_eval: 32
  batch_size: 8
  max_seq_len: 1024
  logging_freq: 10
