_base_: ./generation_gpt_345M_dp8.yaml


Inference:
  model_dir: ./output
  mp_degree: 1

Distributed:
  dp_degree: 
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False
